name: flutter_motion_codelab
description: The reply material study built in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  provider: ^6.0.5
  animations: ^2.0.0
  google_fonts: ^4.0.3
  flutter_gallery_assets: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true


  assets:
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Thin.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-SemiBold.ttf
    - packages/flutter_gallery_assets/reply/attachments/paris_1.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_2.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_3.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_0.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_1.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_2.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_3.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_5.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_6.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_7.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_8.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_9.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_10.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_express.png
    - packages/flutter_gallery_assets/reply/icons/twotone_add_circle_outline.png
    - packages/flutter_gallery_assets/reply/icons/twotone_delete.png
    - packages/flutter_gallery_assets/reply/icons/twotone_drafts.png
    - packages/flutter_gallery_assets/reply/icons/twotone_error.png
    - packages/flutter_gallery_assets/reply/icons/twotone_folder.png
    - packages/flutter_gallery_assets/reply/icons/twotone_forward.png
    - packages/flutter_gallery_assets/reply/icons/twotone_inbox.png
    - packages/flutter_gallery_assets/reply/icons/twotone_send.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star_on_background.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star.png
    - packages/flutter_gallery_assets/reply/icons/twotone_stars.png
    - packages/flutter_gallery_assets/reply/reply_logo.png
